// Autogenerated: do not edit.

package main

import (
	"github.com/d3zd3z/euler/go/pr001"
	"github.com/d3zd3z/euler/go/pr002"
	"github.com/d3zd3z/euler/go/pr003"
	"github.com/d3zd3z/euler/go/pr004"
	"github.com/d3zd3z/euler/go/pr005"
	"github.com/d3zd3z/euler/go/pr006"
	"github.com/d3zd3z/euler/go/pr007"
	"github.com/d3zd3z/euler/go/pr008"
	"github.com/d3zd3z/euler/go/pr009"
	"github.com/d3zd3z/euler/go/pr010"
	"github.com/d3zd3z/euler/go/pr011"
	"github.com/d3zd3z/euler/go/pr012"
	"github.com/d3zd3z/euler/go/pr013"
	"github.com/d3zd3z/euler/go/pr014"
	"github.com/d3zd3z/euler/go/pr015"
	"github.com/d3zd3z/euler/go/pr016"
	"github.com/d3zd3z/euler/go/pr017"
	"github.com/d3zd3z/euler/go/pr018"
	"github.com/d3zd3z/euler/go/pr019"
	"github.com/d3zd3z/euler/go/pr020"
	"github.com/d3zd3z/euler/go/pr021"
	"github.com/d3zd3z/euler/go/pr022"
	"github.com/d3zd3z/euler/go/pr023"
	"github.com/d3zd3z/euler/go/pr024"
	"github.com/d3zd3z/euler/go/pr025"
	"github.com/d3zd3z/euler/go/pr026"
	"github.com/d3zd3z/euler/go/pr027"
	"github.com/d3zd3z/euler/go/pr028"
	"github.com/d3zd3z/euler/go/pr029"
	"github.com/d3zd3z/euler/go/pr030"
	"github.com/d3zd3z/euler/go/pr031"
	"github.com/d3zd3z/euler/go/pr032"
	"github.com/d3zd3z/euler/go/pr033"
	"github.com/d3zd3z/euler/go/pr034"
	"github.com/d3zd3z/euler/go/pr035"
	"github.com/d3zd3z/euler/go/pr036"
	"github.com/d3zd3z/euler/go/pr037"
	"github.com/d3zd3z/euler/go/pr038"
	"github.com/d3zd3z/euler/go/pr039"
	"github.com/d3zd3z/euler/go/pr040"
	"github.com/d3zd3z/euler/go/pr041"
	"github.com/d3zd3z/euler/go/pr042"
	"github.com/d3zd3z/euler/go/pr043"
	"github.com/d3zd3z/euler/go/pr044"
	"github.com/d3zd3z/euler/go/pr045"
	"github.com/d3zd3z/euler/go/pr046"
	"github.com/d3zd3z/euler/go/pr047"
	"github.com/d3zd3z/euler/go/pr048"
	"github.com/d3zd3z/euler/go/pr049"
	"github.com/d3zd3z/euler/go/pr050"
	"github.com/d3zd3z/euler/go/pr051"
	"github.com/d3zd3z/euler/go/pr052"
	"github.com/d3zd3z/euler/go/pr053"
	"github.com/d3zd3z/euler/go/pr055"
	"github.com/d3zd3z/euler/go/pr056"
	"github.com/d3zd3z/euler/go/pr057"
	"github.com/d3zd3z/euler/go/pr058"
	"github.com/d3zd3z/euler/go/pr080"
	"github.com/d3zd3z/euler/go/pr096"
)

var problems = []Problem{
	{1, pr001.Run},
	{2, pr002.Run},
	{3, pr003.Run},
	{4, pr004.Run},
	{5, pr005.Run},
	{6, pr006.Run},
	{7, pr007.Run},
	{8, pr008.Run},
	{9, pr009.Run},
	{10, pr010.Run},
	{11, pr011.Run},
	{12, pr012.Run},
	{13, pr013.Run},
	{14, pr014.Run},
	{15, pr015.Run},
	{16, pr016.Run},
	{17, pr017.Run},
	{18, pr018.Run},
	{19, pr019.Run},
	{20, pr020.Run},
	{21, pr021.Run},
	{22, pr022.Run},
	{23, pr023.Run},
	{24, pr024.Run},
	{25, pr025.Run},
	{26, pr026.Run},
	{27, pr027.Run},
	{28, pr028.Run},
	{29, pr029.Run},
	{30, pr030.Run},
	{31, pr031.Run},
	{32, pr032.Run},
	{33, pr033.Run},
	{34, pr034.Run},
	{35, pr035.Run},
	{36, pr036.Run},
	{37, pr037.Run},
	{38, pr038.Run},
	{39, pr039.Run},
	{40, pr040.Run},
	{41, pr041.Run},
	{42, pr042.Run},
	{43, pr043.Run},
	{44, pr044.Run},
	{45, pr045.Run},
	{46, pr046.Run},
	{47, pr047.Run},
	{48, pr048.Run},
	{49, pr049.Run},
	{50, pr050.Run},
	{51, pr051.Run},
	{52, pr052.Run},
	{53, pr053.Run},
	{55, pr055.Run},
	{56, pr056.Run},
	{57, pr057.Run},
	{58, pr058.Run},
	{80, pr080.Run},
	{96, pr096.Run},
}
