:- module pr002.

% Problem 2
%
% 19 October 2001
%
% Each new term in the Fibonacci sequence is generated by adding the
% previous two terms. By starting with 1 and 2, the first 10 terms will be:
%
% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
%
% By considering the terms in the Fibonacci sequence whose values do not
% exceed four million, find the sum of the even-valued terms.
%
% 4613732

:- interface.
:- import_module io.
:- pred main(io::di, io::uo) is det.

:- implementation.
:- import_module list, int, string.

main(!IO) :-
    solve(1, 1, 0, Answer),
    io.format("%d\n", [i(Answer)], !IO).

:- pred solve(int::in, int::in, int::in, int::out) is det.
solve(A, B, X0, X) :- (
    if
	A > 4000000
    then
	X0 = X
    else if
	even(A)
    then
	solve(B, A+B, X0 + A, X)
    else
	solve(B, A+B, X0, X)
    ).
