----------------------------------------------------------------------
--  Problem 12
--
--  08 March 2002
--
--  The sequence of triangle numbers is generated by adding the natural
--  numbers. So the 7^th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
--  28. The first ten terms would be:
--
--  1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
--
--  Let us list the factors of the first seven triangle numbers:
--
--       1: 1
--       3: 1,3
--       6: 1,2,3,6
--      10: 1,2,5,10
--      15: 1,3,5,15
--      21: 1,3,7,21
--      28: 1,2,4,7,14,28
--
--  We can see that 28 is the first triangle number to have over five
--  divisors.
--
--  What is the value of the first triangle number to have over five hundred
--  divisors?
--
----------------------------------------------------------------------

--  with Ada.Text_IO; use Ada.Text_IO;
with Euler; use Euler;
with Prime_Sieve;

procedure Pr012 is

   function Divisor_Count (Number : Natural) return Natural;

   function Divisor_Count (Number : Natural) return Natural is
      Count : Natural := 1;
      Sv : constant access Prime_Sieve.T := Prime_Sieve.Sieve (Number);
      Prime : Natural := 2;
      Tmp : Natural := Number;
      Divide_Count : Natural;
   begin
      while Tmp > 1 loop
         Divide_Count := 0;
         while Tmp mod Prime = 0 loop
            Tmp := Tmp / Prime;
            Divide_Count := Divide_Count + 1;
         end loop;

         Count := Count * (Divide_Count + 1);

         if Tmp > 1 then
            Prime := Sv.Next_Prime (Prime);
         end if;

      end loop;

      return Count;
   end Divisor_Count;

   Number : Natural := 1;
   Step : Natural := 1;

begin
   Print_Result (Divisor_Count (28));

   loop
      if Divisor_Count (Number) > 500 then
         Print_Result (Number);
         exit;
      end if;

      Step := Step + 1;
      Number := Number + Step;
   end loop;
end Pr012;

