//////////////////////////////////////////////////////////////////////
// Problem 2
// 
// 19 October 2001
// 
// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms
// will be:
// 
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// 
// By considering the terms in the Fibonacci sequence whose values do
// not exceed four million, find the sum of the even-valued terms.
// 
//////////////////////////////////////////////////////////////////////

package pr002

import "fmt"

func Run() {
	a, b := 1, 2
	sum := 0

	for b < 4000000 {
		if b%2 == 0 {
			sum += b
		}
		a, b = b, a+b
	}
	fmt.Printf("%d\n", sum)
}
