// The actual problem list is generated by the build script.  Include it as
// the contents of this module.
//
// Note that the 'mod pr001' declarations in the included file will be
// relative to the included file, not this one, so should generally be full
// paths for each module.
include!(concat!(env!("OUT_DIR"), "/plist.rs"));
