// Problem 44
//
// 23 May 2003
//
//
// Pentagonal numbers are generated by the formula, P[n]=n(3n−1)/2. The first
// ten pentagonal numbers are:
//
// 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
//
// It can be seen that P[4] + P[7] = 22 + 70 = 92 = P[8]. However, their
// difference, 70 − 22 = 48, is not pentagonal.
//
// Find the pair of pentagonal numbers, P[j] and P[k], for which their sum
// and difference is pentagonal and D = |P[k] − P[j]| is minimised; what is
// the value of D?

use misc::isqrt;

define_problem!(pr044, 44, 5482660);

fn pr044() -> u32 {
    for i in 1.. {
        let pent_i = nth_pentagonal(i);
        for j in 1 .. i {
            let pent_j = nth_pentagonal(j);

            if is_pentagonal(pent_i - pent_j) &&
                is_pentagonal(pent_i + pent_j)
            {
                return pent_i - pent_j;
            }
        }
    }
    unreachable!();
}

fn nth_pentagonal(n: u32) -> u32 {
    n * (3*n - 1) / 2
}

fn is_pentagonal(n: u32) -> bool {
    let sq = n * 24 + 1;
    let root = isqrt(sq);
    root*root == sq && (root+1)%6 == 0
}
