% Problem 2
%
% 19 October 2001
%
%
% Each new term in the Fibonacci sequence is generated by adding the
% previous two terms. By starting with 1 and 2, the first 10 terms will be:
%
% 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
%
% By considering the terms in the Fibonacci sequence whose values do not
% exceed four million, find the sum of the even-valued terms.
%
% 4613732

-module(pr002).
-export([solve/0]).

solve() ->
	solve(1, 2, 0). 

solve(_, B, Sum) when B >= 4000000 ->
	Sum;
solve(A, B, Sum) ->
	Next = A + B,
	if
		(B band 1) == 0 ->
			solve(B, Next, Sum + B);
		true ->
			solve(B, Next, Sum)
	end.
