// Problem 2
//
// 19 October 2001
//
// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not
// exceed four million, find the sum of the even-valued terms.
//
// 4613732

#include <iostream>

namespace euler {
namespace pr002 {

void solve()
{
  int answer = 0;
  int a = 1, b = 1;
  while (b < 4000000) {
    if ((b & 1) == 0)
      answer += b;

    int tmp = a + b;
    a = b;
    b = tmp;
  }
  std::cout << answer << "\n";
}

}
}
