;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Problem 2
;;
;; 19 October 2001
;;
;; Each new term in the Fibonacci sequence is generated by adding the
;; previous two terms. By starting with 1 and 2, the first 10 terms
;; will be:
;;
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;
;; By considering the terms in the Fibonacci sequence whose values do
;; not exceed four million, find the sum of the even-valued terms.
;;
;; 4613732
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defpackage #:pr002
  (:use #:cl)
  (:export #:euler-2))

(in-package #:pr002)

(defun euler-2 ()
  (loop
    for a = 1 then b
    and b = 1 then (+ a b)
    while (< b 4000000)
    when (evenp b) summing b))

(euler/problem-set:register-problem 2 #'euler-2 4613732)
