;;; Problem 12
;;;
;;; 08 March 2002
;;;
;;; The sequence of triangle numbers is generated by adding the natural
;;; numbers. So the 7^th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
;;; 28. The first ten terms would be:
;;;
;;; 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
;;;
;;; Let us list the factors of the first seven triangle numbers:
;;;
;;;      1: 1
;;;      3: 1,3
;;;      6: 1,2,3,6
;;;     10: 1,2,5,10
;;;     15: 1,3,5,15
;;;     21: 1,3,7,21
;;;     28: 1,2,4,7,14,28
;;;
;;; We can see that 28 is the first triangle number to have over five
;;; divisors.
;;;
;;; What is the value of the first triangle number to have over five hundred
;;; divisors?
;;;
;;; 76576500

(defpackage #:pr012
  (:use #:cl #:iterate #:euler.sieve)
  (:export #:euler-12))
(in-package #:pr012)

(defun num-divisors (n)
  "Return the number of divisors of N."
  (iter (for p in (factorize n))
	(multiply (1+ (cdr p)))))

(defun euler-12 ()
  (iter (for i from 1)
	(for triangle first 1 then (+ triangle i))
	(when (> (num-divisors triangle) 500)
	  (return-from euler-12 triangle))))

(euler/problem-set:register-problem 12 #'euler-12 76576500)
