      * Problem 2
      *
      * 19 October 2001
      *
      * Each new term in the Fibonacci sequence is generated by adding
      * the previous two terms. By starting with 1 and 2, the first 10
      * terms will be:
      *
      * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
      *
      * By considering the terms in the Fibonacci sequence whose values
      * do not exceed four million, find the sum of the even-valued
      * terms.
      *
       identification division.
       program-id. euler-problem-002.

       data division.
       working-storage section.
       01 a             pic 9(7)  value 1.
       01 b             pic 9(7)  value 1.
       01 temp          pic 9(7).
       01 total         pic 9(7)  value 0.

       procedure division.
           perform until a >= 4000000
                   if function mod (a, 2) = 0 then
                           add a to total
                   end-if
                   perform advance-fibonacci
           end-perform
           display total
           stop run.

       advance-fibonacci.
           add a to b giving temp
           move b to a
           move temp to b.
