(*
 * Problem 45
 *
 * 06 June 2003
 *
 *
 * Triangle, pentagonal, and hexagonal numbers are generated by the
 * following formulae:
 *
 * Triangle     T[n]=n(n+1)/2    1, 3, 6, 10, 15, ...
 * Pentagonal   P[n]=n(3n−1)/2   1, 5, 12, 22, 35, ...
 * Hexagonal    H[n]=n(2n−1)     1, 6, 15, 28, 45, ...
 *
 * It can be verified that T[285] = P[165] = H[143] = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 *
 * 1533776805
 *)

let solve () =
  let rec loop pn hn pentagonal hexagonal =
    if pentagonal == hexagonal && pentagonal > 40755 then
      pentagonal
    else begin
      if pentagonal < hexagonal then
        let pn2 = pn + 1 in
        loop pn2 hn (pentagonal + 3 * pn2 - 2) hexagonal
      else
        let hn2 = hn + 1 in
        loop pn hn2 pentagonal (hexagonal + 4 * hn2 - 3)
    end
  in loop 1 1 1 1

let run () =
  Printf.printf "%d\n" (solve ())
