[project]
name = "euler"
version = "0.0.1"
authors = ["David Brown <davidb@davidb.org>"]
build = "build.rs"

[dependencies]
num = "0.1.31"
rand = "0.3.14"
itertools = "0.4.11"

[build-dependencies]
regex = "0.1.58"

[[bin]]
name = "euler"
