// Autogenerated: do not edit.

package main

import (
	"pr001"
	"pr002"
	"pr003"
	"pr004"
	"pr005"
	"pr006"
	"pr007"
	"pr008"
	"pr009"
	"pr010"
	"pr011"
	"pr012"
	"pr013"
	"pr014"
	"pr015"
	"pr016"
	"pr017"
	"pr018"
	"pr019"
	"pr020"
	"pr021"
	"pr022"
	"pr023"
	"pr024"
	"pr025"
	"pr026"
	"pr027"
	"pr028"
	"pr029"
	"pr030"
	"pr031"
	"pr032"
	"pr033"
	"pr034"
	"pr035"
	"pr036"
	"pr037"
	"pr038"
	"pr039"
	"pr040"
	"pr041"
	"pr042"
	"pr043"
	"pr044"
	"pr045"
	"pr046"
	"pr047"
	"pr048"
	"pr049"
	"pr050"
	"pr051"
	"pr052"
	"pr053"
	"pr055"
	"pr056"
	"pr057"
	"pr080"
	"pr096"
)

var problems = []Problem{
	{1, pr001.Run},
	{2, pr002.Run},
	{3, pr003.Run},
	{4, pr004.Run},
	{5, pr005.Run},
	{6, pr006.Run},
	{7, pr007.Run},
	{8, pr008.Run},
	{9, pr009.Run},
	{10, pr010.Run},
	{11, pr011.Run},
	{12, pr012.Run},
	{13, pr013.Run},
	{14, pr014.Run},
	{15, pr015.Run},
	{16, pr016.Run},
	{17, pr017.Run},
	{18, pr018.Run},
	{19, pr019.Run},
	{20, pr020.Run},
	{21, pr021.Run},
	{22, pr022.Run},
	{23, pr023.Run},
	{24, pr024.Run},
	{25, pr025.Run},
	{26, pr026.Run},
	{27, pr027.Run},
	{28, pr028.Run},
	{29, pr029.Run},
	{30, pr030.Run},
	{31, pr031.Run},
	{32, pr032.Run},
	{33, pr033.Run},
	{34, pr034.Run},
	{35, pr035.Run},
	{36, pr036.Run},
	{37, pr037.Run},
	{38, pr038.Run},
	{39, pr039.Run},
	{40, pr040.Run},
	{41, pr041.Run},
	{42, pr042.Run},
	{43, pr043.Run},
	{44, pr044.Run},
	{45, pr045.Run},
	{46, pr046.Run},
	{47, pr047.Run},
	{48, pr048.Run},
	{49, pr049.Run},
	{50, pr050.Run},
	{51, pr051.Run},
	{52, pr052.Run},
	{53, pr053.Run},
	{55, pr055.Run},
	{56, pr056.Run},
	{57, pr057.Run},
	{80, pr080.Run},
	{96, pr096.Run},
}
