(*
 * Problem 12
 *
 * 08 March 2002
 *
 * The sequence of triangle numbers is generated by adding the natural
 * numbers. So the 7^th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
 * 28. The first ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 *      1: 1
 *      3: 1,3
 *      6: 1,2,3,6
 *     10: 1,2,5,10
 *     15: 1,3,5,15
 *     21: 1,3,7,21
 *     28: 1,2,4,7,14,28
 *
 * We can see that 28 is the first triangle number to have over five
 * divisors.
 *
 * What is the value of the first triangle number to have over five hundred
 * divisors?
 *
 * 76576500
 *)

program pr012;

uses sieve;

var
  sv : SimpleSieve;

  function divisorCount(n : longint) : longint;
  var
    dcount : longint;
    prime : longint = 2;
  begin
    divisorCount := 1;

    while n > 1 do
      begin
	dcount := 0;
	while n mod prime = 0 do
	  begin
	    n := n div prime;
	    dcount := dcount + 1
	  end;

	divisorCount := divisorCount * (dcount + 1);

	if n > 1 then
	  prime := sv.nextPrime(prime)
      end;
  end;

var
  n : longint = 1;
  tri : longint = 1;
begin
  sv := SimpleSieve.create;

  repeat
    if divisorCount(tri) > 500 then
      break;
    n := n + 1;
    tri := tri + n;
  until false;
  writeln(tri)
end.
