# Problem 45
#
# 06 June 2003
#
#
# Triangle, pentagonal, and hexagonal numbers are generated by the following
# formulae:
#
# Triangle     T[n]=n(n+1)/2    1, 3, 6, 10, 15, ...
# Pentagonal   P[n]=n(3n−1)/2   1, 5, 12, 22, 35, ...
# Hexagonal    H[n]=n(2n−1)     1, 6, 15, 28, 45, ...
#
# It can be verified that T[285] = P[165] = H[143] = 40755.
#
# Find the next triangle number that is also pentagonal and hexagonal.
#
# 1533776805

# All hexagonal numbers are triangle numbers, so ignore those.
# To get the nth pentagonal P(n-1) + (3n-2).
# To get the nth hexagonal number H(n-1) + (4n-3).

# We basically track both numbers, decrementing whichever one is
# smaller unti lthey are equal.

function solve()
   pn = 1
   hn = 1
   pentagonal = 1
   hexagonal = 1

   while true
      if pentagonal == hexagonal && pentagonal > 40755
         return pentagonal
      end

      if pentagonal < hexagonal
         pn += 1
         pentagonal += 3pn - 2
      else
         hn += 1
         hexagonal += 4hn - 3
      end
   end
end

println(solve())
