! Problem 2
!
! 19 October 2001
!
! Each new term in the Fibonacci sequence is generated by adding the
! previous two terms. By starting with 1 and 2, the first 10 terms will
! be:
!
! 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
!
! By considering the terms in the Fibonacci sequence whose values do
! not exceed four million, find the sum of the even-valued terms.
! 4613732

program pr002

  implicit none

  integer :: total, a, b, temp

  total = 0
  a = 1
  b = 2

  do while (a < 4000000)
    if (mod (a, 2) == 0) total = total + a

    temp = a + b
    a = b
    b = temp
  end do

  print *, total

end program pr002
